# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'jabareen' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jabareen
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  target 'jabareenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jabareen-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jabareen-tvOS

  target 'jabareen-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
